name: 'GCLOUD-CLI'
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
       contents: read
       pages: write
       id-token: write
       
on:
  push:
    branches:
    - main
  pull_request:

jobs:  
  job_id:
   name: GCLOUD-CLI
   runs-on: ubuntu-latest

   steps:
     # Gcloud Auth
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
     # env:
      # GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      # token_format: 'access_token'
       workload_identity_provider: 'projects/946291750948/locations/global/workloadIdentityPools/github-gcp/providers/github'
       service_account: 'github-sa@mydev-22.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
         version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
